namespace AutoWise.VehiclesCatalog.API.Features.VehicleSpecifications.ImportVehicleSpecifications;

public record ImportVehicleSpecificationsCommand(string Vin) : ICommand<ImportVehicleSpecificationsResult>;
public record ImportVehicleSpecificationsResult(IEnumerable<VehicleSpecification> Specifications);
