<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7074e817-2322-4581-b118-15901a5e6239</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\AutoWise.Users\AutoWise.Users.Infrastructure\Grpc\Protos\users.proto" GrpcServices="Client">
      <Link>Protos\users.proto</Link>
    </Protobuf>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AutoWise.CommonUtilities.ExtensionMethods">
      <HintPath>..\Libraries\AutoWise.CommonUtilities.ExtensionMethods.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
